version: "3.9"
services:
  db:
    image: postgres:16
    container_name: notes_db
    environment:
      POSTGRES_DB: notes_app
      POSTGRES_USER: notes_user
      POSTGRES_PASSWORD: notes_pass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db_data:
    driver: local
